export interface StudentDashboardApiResponse {
  studentId: string;
  organizationId: string;
  studentAttendanceId: string;
  attendanceSessionId: string;
  eventId: string;
  isPresent: boolean;
  eventTitle: string | null;
  eventDescription: string | null;
  eventLocation: string | null;
  eventStartTime: string;
  eventEndTime: string;
  eventType: string | null;
  eventIsActive: boolean;
  assignmentId: string;
  assignmentTitle: string;
  assignmentDescription: string;
  assignmentDueDate: string;
  assignmentTotalMarks: number;
  assignmentSubject: string;
  assignmentCreatedDate: string;
  assignmentSubmissionId: string;
  submissionDate: string;
  assignmentCompleted: boolean;
  assignmentIsPending: boolean;
  assignmentIsSubmitted: boolean;
  assignmentGradesId: string;
  assignmentMarksReceived: number;
  assignmentMarksObtained: number;
  gradedDate: string;
  gradeSubject: string | null;
  messageId: string;
  messageSubject: string;
  messageContent: string;
  messageTimeStamp: string;
  messageIsRead: boolean;
  senderName: string;
  senderRole: string | null;
  academicProgressId: string;
  schoolTerm: string;
  isCurrentTerm: boolean;
  progressSubject: string;
  subjectPercentage: number;
  overallPerfomance: number;
  teacherFirstNames: string;
  teacherLastName: string;
  classSubject: string;
  streamName: string;
  classDate: string;
  classStartTime: string;
  classEndTime: string;
  classRoomNumber: string;
}