import { Routes } from '@angular/router';
import { OrganizationSetupComponent } from './pages/organization-setup/organization-setup.component';
import { LoginComponent } from './pages/authPage/login/login.component';
import { RegisterComponent } from './pages/authPage/register/register.component';
import { ThankYouComponent } from './pages/authPage/thank-you/thank-you.component';
import { RegistrationPaymentComponent } from './pages/payment/registration-payment/registration-payment.component';
import { NetcashPaymentComponent } from './pages/netcash-payment/netcash-payment.component';
import { ForgotPasswordComponent } from './pages/authPage/forgot-password/forgot-password.component';
import { SchoolAdminDashboardComponent } from './pages/dashboards/school-admin-dashboard/school-admin-dashboard.component';
import { AddTeacherComponent } from './pages/dashboards/teachers/add-teacher/add-teacher.component';
import { AddGuestComponent } from './pages/schools/guests/add-guest/add-guest.component';
import { AddLearnerComponent } from './pages/schools/learners/add-learner/add-learner.component';
import { AddStudentComponent } from './pages/schools/students/add-student/add-student.component';
import { AddStuffMemberComponent } from './pages/schools/stuff-members/add-stuff-member/add-stuff-member.component';
import { AdminProfileModalComponent } from './pages/schools/modals/admin-profile-modal/admin-profile-modal.component';
import { ConfirmEmailComponent } from './pages/authPage/confirm-email/confirm-email.component';
import { EditAdminProfileComponent } from './pages/schools/admin/edit-admin-profile/edit-admin-profile.component';
import { AdminSettingsComponent } from './pages/settings/admin-settings/admin-settings.component';
import { LibraryComponent } from './pages/library/library.component';
import { AddGradeModalComponent } from './pages/modals/add-grade-modal/add-grade-modal.component';
import { AddCourseStreamComponent } from './pages/settings/admin-settings/add-course-stream/add-course-stream.component';
import { EditCourseStreamComponent } from './pages/settings/admin-settings/edit-course-stream/edit-course-stream.component';
import { DetailsComponent } from './pages/settings/admin-settings/details/details.component';
import { AddSchoolSubjectComponent } from './pages/settings/admin-settings/add-school-subject/add-school-subject.component';
import { TeacherDashboardComponent } from './pages/dashboards/teacher-dashboard/teacher-dashboard.component';
import { TeacherSettingsComponent } from './pages/settings/teacher-settings/teacher-settings.component';
import { StudentDashboardComponent } from './pages/dashboards/student-dashboard/student-dashboard.component';
import { StudentSettingsComponent } from './pages/settings/student-settings/student-settings.component';
import { CommunicationCenterComponent } from './pages/communication/communication-center.component';
import { AdminReportComponent } from './pages/reports/admin-report/admin-report.component';
import { TeacherReportComponent } from './pages/reports/teacher-report/teacher-report.component';
import { TrainingProgramsComponent } from './pages/training/training-programs.component';
import { CertificationsComponent } from './pages/certifications/certifications.component';
import { ScheduleWorkshopComponent } from './pages/workshops/schedule-workshop.component';
import { JoinWorkshopComponent } from './pages/workshops/join-workshop.component';
import { ManageCoursesComponent } from './pages/courses/manage-courses.component';
import { FaithProgramsComponent } from './pages/faith/faith-programs.component';
import { ComplianceReportsComponent } from './pages/compliance/compliance-reports.component';
import { StaffDevelopmentComponent } from './pages/training/staff-development.component';
import { LeadershipTrainingComponent } from './pages/training/leadership-training.component';
import { ParentDashboardComponent } from './pages/dashboards/parent-dashboard/parent-dashboard.component';
import { ParentSettingsComponent } from './pages/settings/parent-settings/parent-settings.component';
import { ChurchAdminDashboardComponent } from './pages/dashboards/church-admin-dashboard/church-admin-dashboard.component';

export const routes: Routes = [
    { path: '', redirectTo: '/login', pathMatch: 'full' },
    { path: 'login', component: LoginComponent },
    { path: 'register', component: RegisterComponent },
    { path: 'organization-setup', component: OrganizationSetupComponent },
    { path: 'registration-payment', component: RegistrationPaymentComponent },
    { path: 'netcash-payment', component: NetcashPaymentComponent },
    { path: 'thank-you', component: ThankYouComponent },
    { path: 'forgot-password', component: ForgotPasswordComponent },
    { path: 'reset-password', loadComponent: () => import('./pages/authPage/reset-password/reset-password.component').then(m => m.ResetPasswordComponent) },
    { path: 'confirm-email', loadComponent: () => import('./pages/authPage/confirm-email/confirm-email.component').then(m => m.ConfirmEmailComponent) },
    { path: 'school-admin-dashboard', component: SchoolAdminDashboardComponent },
    { path: 'add-teacher', component: AddTeacherComponent },
    { path: 'add-guest', component: AddGuestComponent },
    { path: 'add-learner', component: AddLearnerComponent },
    { path: 'add-student', component: AddStudentComponent },
    { path: 'add-stuff-member', component: AddStuffMemberComponent },
    { path: 'admin-profile-modal', component: AdminProfileModalComponent },
    { path: 'edit-admin-profile', component: EditAdminProfileComponent },
    { path: 'admin-settings', component: AdminSettingsComponent },
    { path: 'library', component: LibraryComponent },
    { path: 'add-grade-modal', component: AddGradeModalComponent },
    { path: 'add-course-stream', component: AddCourseStreamComponent },
    { path: 'edit-course-stream', component: EditCourseStreamComponent },
    { path: 'details', component: DetailsComponent },
    { path: 'add-school-subject', component: AddSchoolSubjectComponent },
    { path: "teacher-dashboard", component: TeacherDashboardComponent },
    { path: "teacher-settings", component: TeacherSettingsComponent },
    { path: "student-dashboard", component: StudentDashboardComponent },
    { path: "student-settings", component: StudentSettingsComponent },
    { path: "communication-center", component: CommunicationCenterComponent },
    { path: "generate-report", component: AdminReportComponent },
    { path: "teacher-report", component: TeacherReportComponent },
    { path: "training-programs", component: TrainingProgramsComponent },
    { path: "certifications", component: CertificationsComponent },
    { path: "schedule-workshop", component: ScheduleWorkshopComponent },
    { path: "join-workshop", component: JoinWorkshopComponent },
    { path: "manage-courses", component: ManageCoursesComponent },
    { path: "faith-programs", component: FaithProgramsComponent },
    { path: "compliance-reports", component: ComplianceReportsComponent },
    { path: "staff-development", component: StaffDevelopmentComponent },
    { path: "leadership-training", component: LeadershipTrainingComponent },
    { path: "parent-dashboard", component: ParentDashboardComponent },
    { path: "parent-settings", component: ParentSettingsComponent },
    { path: "church-admin-dashboard", component: ChurchAdminDashboardComponent },
    { path: '**', redirectTo: 'login' }
];